import './globals.css'
import type { Metadata } from 'next'
import Header from "./components/Header"
import { Akshar } from 'next/font/google'

const akshar = Akshar({
    subsets: ['latin'],
    weight: ['300', '400', '500', '600']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={akshar.className}>
        <Header/>
        {children}
      </body>
    </html>
  )
}
